import os
import logging
import asyncio
from telegram import Update
from telegram.ext import Application, CommandHandler, MessageHandler, filters, ContextTypes
import google.generativeai as genai
from PIL import Image
import io
import requests

# ========================
# CONFIGURATION
# ========================

TOKEN = os.environ.get("TELEGRAM_BOT_TOKEN")
GEMINI_API_KEY = os.environ.get("GEMINI_API_KEY")

if not TOKEN or not GEMINI_API_KEY:
    raise ValueError("Missing TELEGRAM_BOT_TOKEN or GEMINI_API_KEY environment variables!")

# Configure Gemini
genai.configure(api_key=GEMINI_API_KEY)
model = genai.GenerativeModel("gemini-2.0-flash-exp-image-generation")  # Uses Gemini 2.0 Flash with image generation [citation:6]

logging.basicConfig(
    format="%(asctime)s - %(name)s - %(levelname)s - %(message)s", level=logging.INFO
)
logger = logging.getLogger(__name__)

# ========================
# BOT HANDLERS
# ========================

async def start(update: Update, context: ContextTypes.DEFAULT_TYPE):
    """Send a welcome message when /start is issued."""
    welcome_message = (
        "🎨 Welcome to CreatePixelBot!\n\n"
        "Send me a text description, and I'll generate an image for you.\n\n"
        "✨ Tips for best results:\n"
        "• Be specific and descriptive\n"
        "• Mention the style (photorealistic, cartoon, oil painting, etc.)\n"
        "• Include lighting, colors, and composition details\n\n"
        "Example: 'A majestic dragon flying over snow-capped mountains at sunset, photorealistic'"
    )
    await update.message.reply_text(welcome_message)


async def help_command(update: Update, context: ContextTypes.DEFAULT_TYPE):
    """Send a help message."""
    help_text = (
        "🖼️ How to use CreatePixelBot:\n\n"
        "Simply send any text message describing the image you want.\n\n"
        "Examples:\n"
        "• 'Photorealistic sunset over calm ocean waters with seagulls flying'\n"
        "• 'Digital art of a cyberpunk city with neon signs and rain'\n"
        "• 'Oil painting style portrait of an elderly wise wizard'\n\n"
        "Commands:\n"
        "/start - Show welcome message\n"
        "/help - Show this help"
    )
    await update.message.reply_text(help_text)


async def generate_image(update: Update, context: ContextTypes.DEFAULT_TYPE):
    """Generate an image from the user's prompt."""
    prompt = update.message.text
    user = update.message.from_user.first_name

    await update.message.reply_text(f"🎨 Generating image for: '{prompt}'\n⏳ Please wait...")

    try:
        # Generate image using Gemini 2.0 Flash [citation:6]
        response = model.generate_content(
            f"Generate an image: {prompt}",
            generation_config={"temperature": 1.0}
        )

        # Check if response contains image data
        if hasattr(response, "_result") and response._result.candidates:
            for candidate in response._result.candidates:
                if hasattr(candidate, "content") and candidate.content.parts:
                    for part in candidate.content.parts:
                        if hasattr(part, "inline_data") and part.inline_data:
                            # Extract image bytes
                            image_data = part.inline_data.data
                            image_bytes = io.BytesIO(image_data)
                            
                            # Send image back to user
                            await update.message.reply_photo(
                                photo=image_bytes,
                                caption=f"✅ Generated from: '{prompt}'\nGenerated by @CreatePixelBot"
                            )
                            return

        # If no image found, try alternative approach
        await update.message.reply_text("⚠️ Could not generate image. Please try a different prompt.")

    except Exception as e:
        logger.error(f"Error generating image: {e}")
        await update.message.reply_text(
            "❌ Sorry, an error occurred while generating your image. Please try again."
        )


async def handle_image_edit(update: Update, context: ContextTypes.DEFAULT_TYPE):
    """Handle image uploads with captions for editing."""
    if update.message.caption:
        prompt = update.message.caption
        photo = update.message.photo[-1]
        file = await photo.get_file()
        
        await update.message.reply_text(f"🎨 Editing image with prompt: '{prompt}'\n⏳ Please wait...")
        
        # Download image
        image_bytes = await file.download_as_bytearray()
        
        try:
            # Use Gemini to modify the image
            response = model.generate_content([
                prompt,
                Image.open(io.BytesIO(image_bytes))
            ])
            
            # Process response (similar to above)
            if hasattr(response, "_result") and response._result.candidates:
                for candidate in response._result.candidates:
                    if hasattr(candidate, "content") and candidate.content.parts:
                        for part in candidate.content.parts:
                            if hasattr(part, "inline_data") and part.inline_data:
                                image_data = part.inline_data.data
                                image_bytes_out = io.BytesIO(image_data)
                                await update.message.reply_photo(
                                    photo=image_bytes_out,
                                    caption=f"✅ Edited image for: '{prompt}'"
                                )
                                return
            
            await update.message.reply_text("⚠️ Could not edit image. Please try again.")
            
        except Exception as e:
            logger.error(f"Error editing image: {e}")
            await update.message.reply_text("❌ Error editing image. Please try again.")
    else:
        await update.message.reply_text(
            "📷 To edit an image, send an image with a caption describing what you want to change."
        )


async def error_handler(update: Update, context: ContextTypes.DEFAULT_TYPE):
    """Log errors caused by updates."""
    logger.warning(f"Update {update} caused error {context.error}")
    if update and update.message:
        await update.message.reply_text("⚠️ Something went wrong. Please try again.")


# ========================
# MAIN
# ========================

def main():
    """Start the bot."""
    app = Application.builder().token(TOKEN).build()

    # Add command handlers
    app.add_handler(CommandHandler("start", start))
    app.add_handler(CommandHandler("help", help_command))
    
    # Add message handlers
    app.add_handler(MessageHandler(filters.TEXT & ~filters.COMMAND, generate_image))
    app.add_handler(MessageHandler(filters.PHOTO & filters.CAPTION, handle_image_edit))
    
    # Add error handler
    app.add_error_handler(error_handler)

    logger.info("Bot started! @CreatePixelBot is running...")
    app.run_polling()


if __name__ == "__main__":
    main()
